# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login_Page.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from customized import PasswordEdit                                                     #       edited by Dev

from PyQt5.QtCore import Qt


class Ui_Login_Page(object):
    
    def setupUi(self, Login_Page):
        Login_Page.setObjectName("Login_Page")
        Login_Page.resize(650, 755)
        
        # Login_Page.setWindowFlags(QtCore.Qt.FramelessWindowHint)              #       remove the title bar
        
        Login_Page.setStyleSheet("QPushButton#Login_PB{\n"
"    background-color:rgba(85, 98, 112, 255);\n"
"    color:rgba(255, 255, 255, 200);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#Login_PB:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(255, 107, 107, 255);\n"
"    background-position:calc(100% - 10px)center;\n"
"}\n"
"QPushButton#Login_PB:hover{\n"
"    background-color:rgba(255, 107, 107, 255);\n"
"}\n"
"\n"
"QLabel#error_message_Label{\n"
"    color:#cd0000;\n"
"}")
        self.verticalLayoutWidget = QtWidgets.QWidget(Login_Page)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(100, 50, 421, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SMT_Label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.SMT_Label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SMT_Label.sizePolicy().hasHeightForWidth())
        self.SMT_Label.setSizePolicy(sizePolicy)
        self.SMT_Label.setMaximumSize(QtCore.QSize(411, 101))
        self.SMT_Label.setAutoFillBackground(True)
        self.SMT_Label.setStyleSheet("")
        self.SMT_Label.setText("")
        self.SMT_Label.setTextFormat(QtCore.Qt.PlainText)
        self.SMT_Label.setPixmap(QtGui.QPixmap("../Login/Trail_04/icons1/aa.png"))
        self.SMT_Label.setScaledContents(True)
        self.SMT_Label.setObjectName("SMT_Label")
        self.verticalLayout.addWidget(self.SMT_Label)
        self.username_Label = QtWidgets.QLabel(Login_Page)
        self.username_Label.setGeometry(QtCore.QRect(150, 280, 341, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.username_Label.setFont(font)
        self.username_Label.setStyleSheet("")
        self.username_Label.setObjectName("username_Label")
        self.username_LineEdit = QtWidgets.QLineEdit(Login_Page)
        self.username_LineEdit.setGeometry(QtCore.QRect(150, 310, 341, 51))
        self.username_LineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.username_LineEdit.setObjectName("username_LineEdit")
        self.Login_PB = QtWidgets.QPushButton(Login_Page)
        self.Login_PB.setGeometry(QtCore.QRect(150, 540, 341, 51))
        self.Login_PB.setStyleSheet("border-radius:20px;\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.Login_PB.setObjectName("Login_PB")
        self.password_Label = QtWidgets.QLabel(Login_Page)
        self.password_Label.setGeometry(QtCore.QRect(150, 380, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.password_Label.setFont(font)
        self.password_Label.setStyleSheet("")
        self.password_Label.setObjectName("password_Label")
        
        # self.password_LineEdit = QtWidgets.QLineEdit(Login_Page)                                            #       edited by Dev
        self.password_LineEdit = PasswordEdit(Login_Page)
        
        self.password_LineEdit.setGeometry(QtCore.QRect(150, 410, 341, 51))
        self.password_LineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.password_LineEdit.setObjectName("password_LineEdit")
        self.Forgot_Password_PB = QtWidgets.QPushButton(Login_Page)
        self.Forgot_Password_PB.setGeometry(QtCore.QRect(150, 610, 341, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Forgot_Password_PB.setFont(font)
        self.Forgot_Password_PB.setStyleSheet("border-radius:20px;\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.Forgot_Password_PB.setObjectName("Forgot_Password_PB")
        self.error_message_Label = QtWidgets.QLabel(Login_Page)
        self.error_message_Label.setGeometry(QtCore.QRect(150, 490, 400, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.error_message_Label.setFont(font)
        self.error_message_Label.setStyleSheet("")
        self.error_message_Label.setWordWrap(True)
        self.error_message_Label.setObjectName("error_message_Label")

        self.retranslateUi(Login_Page)
        QtCore.QMetaObject.connectSlotsByName(Login_Page)
        Login_Page.setTabOrder(self.username_LineEdit, self.password_LineEdit)
        Login_Page.setTabOrder(self.password_LineEdit, self.Login_PB)
        Login_Page.setTabOrder(self.Login_PB, self.Forgot_Password_PB)
        
    def closeEvent(self, event):
        print("i am in login_UI 130 closeevent")
        # self.closed.emit()

    def retranslateUi(self, Login_Page):
        _translate = QtCore.QCoreApplication.translate
        Login_Page.setWindowTitle(_translate("Login_Page", "Login Page"))
        self.username_Label.setText(_translate("Login_Page", "Admin Username"))
        self.Login_PB.setText(_translate("Login_Page", "Log in"))
        self.password_Label.setText(_translate("Login_Page", "Password"))
        self.Forgot_Password_PB.setText(_translate("Login_Page", "Forgot Password ?"))
        self.error_message_Label.setText(_translate("Login_Page", "error"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login_Page = QtWidgets.QWidget()
    ui = Ui_Login_Page()
    ui.setupUi(Login_Page)
    Login_Page.show()    
    
    sys.exit(app.exec_())
