# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Recipe_create_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Recipe_create_page(object):
    def setupUi(self, Recipe_create_page):
        Recipe_create_page.setObjectName("Recipe_create_page")
        Recipe_create_page.resize(647, 685)
        
        # Recipe_create_page.setWindowFlags(QtCore.Qt.FramelessWindowHint)              #       remove the title bar
        
        Recipe_create_page.setStyleSheet("/* Set style for function widget */\n"
"#widget{\n"
"    background-color:#fff;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"/* Set style for QLabel */\n"
"QLabel{\n"
"    color:#767e89\n"
"}\n"
"\n"
"QLabel#error_message_Label{\n"
"    color:#cd0000;\n"
"}\n"
"\n"
"/* Set style for QLineEdit */\n"
"QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 2px solid #cccccc;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border-bottom: 2px solid #28a2a2;\n"
"}\n"
"\n"
"/* Set style for QPushButton */\n"
"QPushButton#save_PB {\n"
"    background-color: #0d6efd;\n"
"    border:  2px solid#fff;\n"
"    color:#fff;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"    margin-top: 10px;\n"
"}\n"
"\n"
"QPushButton#close_PB {\n"
"    background-color: #ff0000;\n"
"    border:  2px solid#fff;\n"
"    color:#fff;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover,\n"
"QPushButton:clicked{\n"
"    background-color: #0b5ed7;\n"
"    border:  2px solid #9ac3fe;\n"
"}")
        self.layoutWidget = QtWidgets.QWidget(Recipe_create_page)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 611, 541))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.save_PB = QtWidgets.QPushButton(self.layoutWidget)
        self.save_PB.setObjectName("save_PB")
        self.gridLayout.addWidget(self.save_PB, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 90, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.close_PB = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_PB.sizePolicy().hasHeightForWidth())
        self.close_PB.setSizePolicy(sizePolicy)
        self.close_PB.setMinimumSize(QtCore.QSize(35, 40))
        self.close_PB.setMaximumSize(QtCore.QSize(35, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.close_PB.setFont(font)
        self.close_PB.setStyleSheet("")
        self.close_PB.setIconSize(QtCore.QSize(20, 20))
        self.close_PB.setFlat(True)
        self.close_PB.setObjectName("close_PB")
        self.gridLayout.addWidget(self.close_PB, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.recipe_name_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.recipe_name_lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.recipe_name_lineEdit.setObjectName("recipe_name_lineEdit")
        self.gridLayout_3.addWidget(self.recipe_name_lineEdit, 0, 1, 1, 1)
        self.recipe_name_Label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recipe_name_Label.sizePolicy().hasHeightForWidth())
        self.recipe_name_Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.recipe_name_Label.setFont(font)
        self.recipe_name_Label.setStyleSheet("")
        self.recipe_name_Label.setObjectName("recipe_name_Label")
        self.gridLayout_3.addWidget(self.recipe_name_Label, 0, 0, 1, 1)
        self.motion_diretion_Label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.motion_diretion_Label.sizePolicy().hasHeightForWidth())
        self.motion_diretion_Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.motion_diretion_Label.setFont(font)
        self.motion_diretion_Label.setStyleSheet("")
        self.motion_diretion_Label.setObjectName("motion_diretion_Label")
        self.gridLayout_3.addWidget(self.motion_diretion_Label, 1, 0, 1, 1)
        self.distance_Label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.distance_Label.sizePolicy().hasHeightForWidth())
        self.distance_Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.distance_Label.setFont(font)
        self.distance_Label.setStyleSheet("")
        self.distance_Label.setObjectName("distance_Label")
        self.gridLayout_3.addWidget(self.distance_Label, 3, 0, 1, 1)
        self.distance_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.distance_lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.distance_lineEdit.setObjectName("distance_lineEdit")
        self.gridLayout_3.addWidget(self.distance_lineEdit, 3, 1, 1, 1)
        self.speed_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.speed_lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.speed_lineEdit.setObjectName("speed_lineEdit")
        self.gridLayout_3.addWidget(self.speed_lineEdit, 2, 1, 1, 1)
        self.speed_Label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speed_Label.sizePolicy().hasHeightForWidth())
        self.speed_Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.speed_Label.setFont(font)
        self.speed_Label.setStyleSheet("")
        self.speed_Label.setObjectName("speed_Label")
        self.gridLayout_3.addWidget(self.speed_Label, 2, 0, 1, 1)
        self.motion_direction_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.motion_direction_comboBox.sizePolicy().hasHeightForWidth())
        self.motion_direction_comboBox.setSizePolicy(sizePolicy)
        self.motion_direction_comboBox.setMaximumSize(QtCore.QSize(16777215, 30))
        self.motion_direction_comboBox.setObjectName("motion_direction_comboBox")
        self.gridLayout_3.addWidget(self.motion_direction_comboBox, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.error_message_Label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.error_message_Label.setFont(font)
        self.error_message_Label.setStyleSheet("")
        self.error_message_Label.setWordWrap(True)
        self.error_message_Label.setObjectName("error_message_Label")
        self.gridLayout.addWidget(self.error_message_Label, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem3, 3, 0, 1, 1)

        self.retranslateUi(Recipe_create_page)
        QtCore.QMetaObject.connectSlotsByName(Recipe_create_page)

    def retranslateUi(self, Recipe_create_page):
        _translate = QtCore.QCoreApplication.translate
        Recipe_create_page.setWindowTitle(_translate("Recipe_create_page", "User Registration"))
        self.save_PB.setText(_translate("Recipe_create_page", "Save"))
        self.close_PB.setText(_translate("Recipe_create_page", "x"))
        self.recipe_name_Label.setText(_translate("Recipe_create_page", "Recipe Name"))
        self.motion_diretion_Label.setText(_translate("Recipe_create_page", "Motion Direction"))
        self.distance_Label.setText(_translate("Recipe_create_page", "Distance (mm)"))
        self.speed_Label.setText(_translate("Recipe_create_page", "Speed (mm/s)"))
        self.error_message_Label.setText(_translate("Recipe_create_page", "error"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Recipe_create_page = QtWidgets.QWidget()
    ui = Ui_Recipe_create_page()
    ui.setupUi(Recipe_create_page)
    Recipe_create_page.show()
    sys.exit(app.exec_())
