# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'User_profile_create_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from customized import PasswordEdit                                                     #       edited by Dev


class Ui_User_profile_create_page(object):
    def setupUi(self, User_profile_create_page):
        User_profile_create_page.setObjectName("User_profile_create_page")
        User_profile_create_page.resize(647, 754)
        
        User_profile_create_page.setWindowFlags(QtCore.Qt.FramelessWindowHint)              #       remove the title bar
        
        User_profile_create_page.setStyleSheet("/* Set style for function widget */\n"
"#widget{\n"
"    background-color:#fff;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"/* Set style for QLabel */\n"
"QLabel{\n"
"    color:#767e89\n"
"}\n"
"\n"
"QLabel#error_message_Label{\n"
"    color:#cd0000;\n"
"}\n"
"\n"
"/* Set style for QLineEdit */\n"
"QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 2px solid #cccccc;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border-bottom: 2px solid #28a2a2;\n"
"}\n"
"\n"
"/* Set style for QPushButton */\n"
"QPushButton#login_PB {\n"
"    background-color: #0d6efd;\n"
"    border:  2px solid#fff;\n"
"    color:#fff;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"    margin-top: 10px;\n"
"}\n"
"\n"
"QPushButton#close_PB {\n"
"    background-color: #ff0000;\n"
"    border:  2px solid#fff;\n"
"    color:#fff;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover,\n"
"QPushButton:clicked{\n"
"    background-color: #0b5ed7;\n"
"    border:  2px solid #9ac3fe;\n"
"}")
        self.layoutWidget = QtWidgets.QWidget(User_profile_create_page)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 611, 661))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.close_PB = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_PB.sizePolicy().hasHeightForWidth())
        self.close_PB.setSizePolicy(sizePolicy)
        self.close_PB.setMinimumSize(QtCore.QSize(35, 40))
        self.close_PB.setMaximumSize(QtCore.QSize(35, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.close_PB.setFont(font)
        self.close_PB.setStyleSheet("")
        self.close_PB.setIconSize(QtCore.QSize(20, 20))
        self.close_PB.setFlat(True)
        self.close_PB.setObjectName("close_PB")
        self.gridLayout.addWidget(self.close_PB, 0, 4, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.first_name_Label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.first_name_Label.setFont(font)
        self.first_name_Label.setStyleSheet("")
        self.first_name_Label.setObjectName("first_name_Label")
        self.verticalLayout.addWidget(self.first_name_Label)
        self.first_name_LineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.first_name_LineEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.first_name_LineEdit.sizePolicy().hasHeightForWidth())
        self.first_name_LineEdit.setSizePolicy(sizePolicy)
        self.first_name_LineEdit.setMinimumSize(QtCore.QSize(400, 0))
        self.first_name_LineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.first_name_LineEdit.setInputMask("")
        self.first_name_LineEdit.setText("")
        self.first_name_LineEdit.setObjectName("first_name_LineEdit")
        self.verticalLayout.addWidget(self.first_name_LineEdit)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Last_name_Label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Last_name_Label.setFont(font)
        self.Last_name_Label.setStyleSheet("")
        self.Last_name_Label.setObjectName("Last_name_Label")
        self.verticalLayout_2.addWidget(self.Last_name_Label)
        self.Last_name_LineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.Last_name_LineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.Last_name_LineEdit.setObjectName("Last_name_LineEdit")
        self.verticalLayout_2.addWidget(self.Last_name_LineEdit)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.username_Label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.username_Label.setFont(font)
        self.username_Label.setStyleSheet("")
        self.username_Label.setObjectName("username_Label")
        self.verticalLayout_3.addWidget(self.username_Label)
        self.username_LineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.username_LineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.username_LineEdit.setObjectName("username_LineEdit")
        self.verticalLayout_3.addWidget(self.username_LineEdit)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.password_Label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.password_Label.setFont(font)
        self.password_Label.setStyleSheet("")
        self.password_Label.setObjectName("password_Label")
        self.verticalLayout_4.addWidget(self.password_Label)
        
        # self.password_LineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        # self.password_LineEdit = QtWidgets.QLineEdit(self.bgwidget)                                             #       edited by Dev
        self.password_LineEdit = PasswordEdit(self.layoutWidget)                                                    #       edited by Dev
        
        self.password_LineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.password_LineEdit.setObjectName("password_LineEdit")
        self.verticalLayout_4.addWidget(self.password_LineEdit)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.confirm_password_Label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.confirm_password_Label.setFont(font)
        self.confirm_password_Label.setStyleSheet("")
        self.confirm_password_Label.setObjectName("confirm_password_Label")
        self.verticalLayout_5.addWidget(self.confirm_password_Label)
        
        # self.confirm_password_LineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        # self.password_LineEdit = QtWidgets.QLineEdit(self.bgwidget)                                             #       edited by Dev
        self.confirm_password_LineEdit = PasswordEdit(self.layoutWidget)                                                    #       edited by Dev
        self.confirm_password_LineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.confirm_password_LineEdit.setObjectName("confirm_password_LineEdit")
        self.verticalLayout_5.addWidget(self.confirm_password_LineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.error_message_Label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.error_message_Label.setFont(font)
        self.error_message_Label.setStyleSheet("")
        self.error_message_Label.setWordWrap(True)
        self.error_message_Label.setObjectName("error_message_Label")
        self.verticalLayout_5.addWidget(self.error_message_Label)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.login_PB = QtWidgets.QPushButton(self.layoutWidget)
        self.login_PB.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.login_PB.setFont(font)
        self.login_PB.setObjectName("login_PB")
        self.verticalLayout_5.addWidget(self.login_PB)
        self.password_criteria_Label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(6)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.password_criteria_Label.setFont(font)
        self.password_criteria_Label.setStyleSheet("")
        self.password_criteria_Label.setWordWrap(True)
        self.password_criteria_Label.setObjectName("password_criteria_Label")
        self.verticalLayout_5.addWidget(self.password_criteria_Label)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout_6, 3, 1, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 4, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 1, 4, 1, 1)

        self.retranslateUi(User_profile_create_page)
        QtCore.QMetaObject.connectSlotsByName(User_profile_create_page)

    def retranslateUi(self, User_profile_create_page):
        _translate = QtCore.QCoreApplication.translate
        User_profile_create_page.setWindowTitle(_translate("User_profile_create_page", "User Registration"))
        self.close_PB.setText(_translate("User_profile_create_page", "x"))
        self.first_name_Label.setText(_translate("User_profile_create_page", "First Name"))
        self.Last_name_Label.setText(_translate("User_profile_create_page", "Last Name"))
        self.username_Label.setText(_translate("User_profile_create_page", "Username"))
        self.password_Label.setText(_translate("User_profile_create_page", "Password"))
        self.confirm_password_Label.setText(_translate("User_profile_create_page", "Confirm Password"))
        self.error_message_Label.setText(_translate("User_profile_create_page", "error"))
        self.login_PB.setText(_translate("User_profile_create_page", "Login"))
        self.password_criteria_Label.setText(_translate("User_profile_create_page", "The password must contain one uppercase letter, one lowercase letter, one numeric letter, one special character."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    User_profile_create_page = QtWidgets.QWidget()
    ui = Ui_User_profile_create_page()
    ui.setupUi(User_profile_create_page)
    User_profile_create_page.show()
    sys.exit(app.exec_())
