# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Welcome_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(650, 755)
        Form.setStyleSheet("")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(110, 90, 421, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SMT_Label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.SMT_Label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SMT_Label.sizePolicy().hasHeightForWidth())
        self.SMT_Label.setSizePolicy(sizePolicy)
        self.SMT_Label.setMaximumSize(QtCore.QSize(411, 101))
        self.SMT_Label.setAutoFillBackground(True)
        self.SMT_Label.setStyleSheet("")
        self.SMT_Label.setText("")
        self.SMT_Label.setTextFormat(QtCore.Qt.PlainText)
        self.SMT_Label.setPixmap(QtGui.QPixmap("../Login/Trail_04/icons1/aa.png"))
        self.SMT_Label.setScaledContents(True)
        self.SMT_Label.setObjectName("SMT_Label")
        self.verticalLayout.addWidget(self.SMT_Label)
        self.Admin_PB = QtWidgets.QPushButton(Form)
        self.Admin_PB.setGeometry(QtCore.QRect(150, 340, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.Admin_PB.setFont(font)
        self.Admin_PB.setStyleSheet("")
        self.Admin_PB.setObjectName("Admin_PB")
        self.Manager_PB = QtWidgets.QPushButton(Form)
        self.Manager_PB.setGeometry(QtCore.QRect(150, 440, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Manager_PB.setFont(font)
        self.Manager_PB.setStyleSheet("")
        self.Manager_PB.setObjectName("Manager_PB")
        self.Operator_PB = QtWidgets.QPushButton(Form)
        self.Operator_PB.setGeometry(QtCore.QRect(150, 540, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Operator_PB.setFont(font)
        self.Operator_PB.setStyleSheet("")
        self.Operator_PB.setObjectName("Operator_PB")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "SMT Software"))
        self.Admin_PB.setText(_translate("Form", "Admin"))
        self.Manager_PB.setText(_translate("Form", "Manager"))
        self.Operator_PB.setText(_translate("Form", "Operator"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
